### ISSUE TITLE
link relations: acl, describedby and meta

### ISSUE THREAD

**Issue by elf-pavlik** [solid/solid-spec#10]
### Background

https://github.com/linkeddata/SoLiD#wac
```
HTTP/1.1 200 OK
....
Link: <https://example.org/data/.acl>; rel="acl"
Link: <https://example.org/data/.meta>; rel="describedby"
```

https://github.com/linkeddata/SoLiD#pubsub-notifications
```
HTTP/1.1 200 OK
...
Updates-Via: wss://example.org/
```

### Questions

1. Do you plan to register **acl** and **describedby** link relations with IANA and/or microformats.org?
2. Will link relations **acl** and **describedby** also have full URI e.g. to use them in RDF
3. How rel="describedby" differs from rel="meta"?
4. Why choice of Updates-Via header and not for example link rel="updates-via"?
5. Why .meta and .acl naming conventions if we can find relevant resources via link relations?

### seeAlso
* http://patterns.dataincubator.org/book/autodiscovery.html
* http://www.iana.org/assignments/link-relations/link-relations.xhtml
* http://microformats.org/wiki/existing-rel-values
* https://github.com/mnot/I-D/issues/39
* https://github.com/w3c/csvw/issues/297

**Comment by deiu** [comment]
1. Eventually, yes. 
2. If we can't register them, then yes, we need to provide a link for people to find more information about these relations.
3. Describedby is used by LDP, and is also registered with IANA.
4. No good answer at this point. We could switch to Link headers.
5. Because it's easier to notice them while browsing the filesystem when not using the Web. Servers should also hide the .meta/.acl resources when clients view containers.

**Comment by elf-pavlik** [comment]
Hi @deiu 

Since describedby and acl will very unlikely have have URIs assigned by IANA, I don't see way to use them outside of HTTP Header (e.g in Turtle/JSON-LD/RDFa). Looking at definition of [describedby](http://www.w3.org/TR/ldp/#link-relation-describedby) I wonder if one could use it to relate binary image to a social artifact it encodes. By social artifact I mean URI which one can use to like, comment on, see number of likes and views etc. Pretty much reverse of [schema:contentUrl](http://schema.org/contentUrl)
https://www.w3.org/wiki/Socialwg/MediaObject#Problem_Definition

**Comment by elf-pavlik** [comment]
I understand that while this spec recommends URI pattern of .meta and .acl and shows hosting them all on a single domain/server. At the same time, if one has reason for dong so, than can also choose to publish meta and acl resources **anywhere** on The Web and use opaque IRIs
e.g. on three different domains **red**.tld, **green**.tld, **blue**.tld hosted on three different physical machines, using /{UUID} pattern for IRIs

REQUEST:
```
HEAD /90476f4f-56d2-493d-957b-f962d232ee6d HTTP/1.1
Host: red.tld
```

RESPONSE:
```
HTTP/1.1 200 OK
....
Link: <https://green.tld/4d9973c4-8643-41fa-b184-6b1e8c2ad2f9>; rel="acl"
Link: <https://blue.tld/038536f7-7ffe-4ad9-a042-1f998e09b16b>; rel="describedby"

**Comment by deiu** [comment]
Sure, Linked Data gives you this freedom, though from a security & privacy p.o.v. I'm not sure how well it will work.

**Comment by dmitrizagidulin** [comment]
Have the questions here been answered - can this issue be closed?

**Comment by dmitrizagidulin** [comment]
Closing issue. Please reopen on [solid/issues](https://github.com/solid/solid/issues/) if there's still questions on this subject.
