### ISSUE TITLE
Ensure that all repositories use ldp:inbox

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid-spec#108]
#107 captures in the spec that ldp:inbox has replaced solid:inbox.
However, some repos still need updates:

- [x] solid/node-solid-server (https://github.com/solid/node-solid-server/pull/794)
- [x] solid/solid-inbox/ (https://github.com/solid/solid-inbox/pull/4)
- [x] solid/solid-client (https://github.com/solid/solid-client/pull/155)
- [x] solid/solid (https://github.com/solid/solid/pull/154)
- [ ] …

**Comment by RubenVerborgh** [comment]
Fixed node-solid-server: https://github.com/solid/node-solid-server/pull/794

**Comment by RubenVerborgh** [comment]
Fixed solid-inbox: https://github.com/solid/solid-inbox/pull/4

**Comment by RubenVerborgh** [comment]
Fixed solid-client: https://github.com/solid/solid-client/pull/155

**Comment by RubenVerborgh** [comment]
All of our repositories that were touched in the last year have been updated:
- https://github.com/search?q=org%3Asolid+%22terms+inbox%22&type=Code
- https://github.com/search?q=org%3Alinkeddata+%22terms+inbox%22&type=Code
- https://github.com/search?q=org%3Asolid+%22solid+inbox%22&type=Code
- https://github.com/search?q=org%3Alinkeddata+%22solid+inbox%22&type=Code

**Comment by melvincarvalho** [comment]
Discussed this with @RubenVerborgh out of band

So there's 2 possible strategies

- switch solid : inbox to solid : ldp
- Allow clients to support both the old predicate and the new (safer)

However solid : inbox is not identical to solid : ldp -- the former is an entry in an vocab, the latter is a 20 page spec.  And they have different attack surfaces.  So, outside of solid, it's up to app devs which they want to use.

**Comment by RubenVerborgh** [comment]
As discusses in https://github.com/solid/vocab/issue/31 and https://github.com/solid/vocab/pull/33, it's ldp:inbox now. Rebasing and merging.
