### ISSUE TITLE
Check for more archaic artifacts

### ISSUE THREAD

**Issue by kjetilk** [solid/solid-spec#109]
Following #108 , I think we should do a little fossil hunt for NSS 5.0.0, since it should be a state-of-the-art release that clients can rely on for the latest best practices, even if it is prototypical in terms of stability and security. 

Are there more things like #107 that we should fix before NSS 5.0.0 is released?

**Comment by gobengo** [comment]
Clarifying the itended capabilities/limitations of globbing is probably relevant to what goes into the next major semver.

**Comment by kjetilk** [comment]
With the new effort, this issue is obsolete.
