### ISSUE TITLE
Link to specs from official website

### ISSUE THREAD

**Issue by remram44** [solid/solid-spec#110]
*(disclaimer: I'm sorry for posting it here, but the canonical website at Inrupt has no linked repository or contact info. Surprising for an open web movement, but hopefully this bug tracker is ok)*

The [official website](https://solid.inrupt.com/) has very limited documentation for now, and is no replacement for this specification. While a whole page (out of 4) is a dedicated "Introduction to the Solid Specification", it does not link to said specifications, and neither does any page of the website (including the "developer resources", which just takes you to said docs). The only way to find this is to go through "Solid on GitHub" and search through the 3 pages of repositories.

I think a link to this (open!) specification would be a great addition to the website. I hope you consider it!

**Comment by RubenVerborgh** [comment]
Thanks @remram44, links added to https://solid.inrupt.com/docs/intro-to-solid-spec. The website is still very much a work in progress, so that's why there are still gaps like this.

**Comment by kjetilk** [comment]
Great catch, @remram44 ! Yeah, I think this link makes an awful lot of sense, because I saw some critisism that it was hard to understand what it does technically.
