### ISSUE TITLE
How are inboxes handled?

### ISSUE THREAD

**Issue by evanp** [solid/solid-spec#14]
Per the inbox user story:

https://www.w3.org/wiki/Socialwg/Social_API/User_stories#Inbox

At the last F2F, we saw an example where the Web-based client was responsible for aggregating the streams of everyone a user follows into a stream. Is this the plan for SoLiD?

**Comment by deiu** [comment]
We're aware there are certain limitation in SoLid when it comes to scaling the aggregation process. We're  currently looking into a way to have the server do this for the client. Basically, clients would tell the server to subscribe to external resources, so that aggregation happens on the server.

**Comment by dmitrizagidulin** [comment]
Moving to [solid/26: Document/provide recommended workflow for Decentralized Aggregation](https://github.com/solid/solid/issues/26) and [issues/25: Develop recommended Inbox semantics](https://github.com/solid/solid/issues/25). Closing.
