### ISSUE TITLE
Refer to SPARQL Update

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-spec#159]
The spec says it's based on LDP, and LDP prefers [LD-PATCH](https://www.w3.org/TR/ldpatch/) and that document lists a number of alternatives, namely Sparql UPDATE, SparqlPatch, TurtlePatch, and RDF Patch. @kjetilk also proposed RDF-merge in #120.

However, https://github.com/solid/solid-spec/blob/master/api-rest.md#alternative-using-sparql-1 quotes an example that has 'DELETE DATA' and 'INSERT DATA', and it looks like that's Sparql Update. So should we explicitly say that:
1) Although Solid servers need to support LDP basic containers, they don't need to support LD-PATCH
2) Solid servers do need to support https://www.w3.org/TR/sparql11-update/

**Comment by michielbdejong** [comment]
Node-Solid-Server also implements [n3-patch](https://github.com/solid/node-solid-server/blob/master/lib/handlers/patch/n3-patch-parser.js) which seems to be different from RDF patch, and relies on http://www.w3.org/ns/solid/terms#inserts, http://www.w3.org/ns/solid/terms#deletes, and http://www.w3.org/ns/solid/terms#where which seems pretty custom and undocumented?

**Comment by kjetilk** [comment]
SPARQL 1.1 Update is a major requirement on servers. As a SPARQL fan, I'd love to say yes, but it also puts some stress on the WAC implementation. So, I'm not sure we could do it.

**Comment by michielbdejong** [comment]
>  I'm not sure we could do it.

So indeed it wasn't easy, but I managed to do it in wac-ldp, now using three different RDF libraries (rdf-ext for the basics, comunica for sparql GET queries, and rdflib.js for sparql-update).

**Comment by kjetilk** [comment]
The discussion should now continue in the new issue autolinked above. :-)
