### ISSUE TITLE
acl is not an IANA-registered link relation

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid-spec#183]
via @nickshanks:

"acl" is not an IANA-registered link relation, used on https://github.com/solid/solid-spec/blob/master/content-representation.md
It needs to either be registereed, or changed to a custom URI as the link relation. ("describedby" is registered, FWIW, and I presume you are using it in the context it was registered for)
Also, I suspect that "access" would be a better link relation to register, as it is more technology agnostic and so could cover more use cases.

**Comment by elf-pavlik** [comment]
I think some conversation on that topic already happened in https://github.com/solid/web-access-control-spec/issues/21

**Comment by kjetilk** [comment]
> I think some conversation on that topic already happened in [solid/web-access-control-spec#21](https://github.com/solid/web-access-control-spec/issues/21)

Indeed. Are you OK with closing this issue and keeping the entire discussion there, @RubenVerborgh ?

**Comment by RubenVerborgh** [comment]
Thanks, will copy text there.
