### ISSUE TITLE
moving some responsibilities from client Apps to proxies

### ISSUE THREAD

**Issue by elf-pavlik** [solid/solid-spec#20]
just as Loqi bot on IRC uses generic server to make clients simpler but still look as part of the server... i will elaborate more soon!

also see work in recently started https://www.w3.org/community/decsharing/

**Comment by elf-pavlik** [comment]
I will deploy soon a setup where I use multiple backends
1) data only - pretty much LDP with minimal additions
2) rendering (read only) proxy - if request to data only backend comes for text/html it will do HTTP 303 to such rendering backend which will in teurn get data from first backend (if not cached) and render HTML :eyeglasses: 

In data backend I will most likely still use 303 to redirect to .jsonld .ttl etc. 
Also for now I for data which has no rendering proxy with a HTML template, I will redirect to [JSON-LD Playground](http://json-ld.org/playground/) Using UriTemplate to make it fetch data from data only backend :exclamation: 

Please expect more updates here including architecture diagrams with some sequence diagrams! @bblfish @melvincarvalho 

I find this approach in many ways similar to common pattern of separating API (audience: machine agents) from Web Pages (audience: human agents)

Data | Presentation
------- | -----------------
http://graph.facebook.com/ | http://facebook.com/
https://api.github.com/ | https://github.com/
https://api.twitter.com/ | https://twitter.com/

etc.

Just following Link Data patterns and leveraging HTTP 303 and [describedBy](http://www.w3.org/TR/ldp/#link-relation-describedby)/[describes](https://tools.ietf.org/html/rfc6892) link relations :)

While it should work very smooth for reading public data, I still need to explore challenges of working with resources which use ACL.

**Comment by dmitrizagidulin** [comment]
@elf-pavlik - we're in the process of moving issues from `solid-spec/issues` to `solid/issues`. 
I'm not sure what to do with this one - what's the action item here?
Do you mind closing this one (and opening a more concrete one on http://github.com/solid/solid/issues ?)

**Comment by dmitrizagidulin** [comment]
Closing. Feel free to reopen on https://github.com/solid/solid/issues if there's further steps to be taken on this one.
