### ISSUE TITLE
redirect from example.com/foo to example.com/foo/ where appropriate

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-spec#208]
As per https://github.com/inrupt/wac-ldp/issues/136#issuecomment-516619360 this is something the databrowser expects a pod server to do.

**Comment by RubenVerborgh** [comment]
Could you make a spec note too?

**Comment by michielbdejong** [comment]
What is a spec note? A PR that adds a note to the spec, you mean?

**Comment by michielbdejong** [comment]
Also, thinking whether a redirect in the opposite direction would make sense in the opposite case.

**Comment by michielbdejong** [comment]
PR created ^

**Comment by csarven** [comment]
This optional behaviour is stated in https://solidproject.org/TR/protocol
