### ISSUE TITLE
SoLiD ontologies

### ISSUE THREAD

**Issue by bblfish** [solid/solid-spec#22]
We need to have coherence in the ontologies we use so that our apps can work together . At the minimum we need to list the ontologies which apps are using, with perhaps descriptions of the problems found in those ontologies. This can help us choose interoperable ontologies. We should also document how different apps use them, so that we can start gathering patterns of deployment.

**Comment by csarven** [comment]
I didn't notice this issue when I created https://github.com/solid/vocab . Same intention.

**Comment by dmitrizagidulin** [comment]
Given that we have the `solid/vocab` repo for the anthologies, can we close this issue?

**Comment by bblfish** [comment]
yep fine. Thanks.
