### ISSUE TITLE
Identify Solid Server and Spec Version

### ISSUE THREAD

**Issue by CxRes** [solid/solid-spec#223]
I suspect Solid will turn out to be a living standard that shall undergo many changes over the course of its lifetime. Therefore, it would be necessary that in response to HTTP requests, the server identify that it implements Solid and the version of the spec it complies to! At least, I could not find any such requirement in the specification.

Currently NSS provides a `x-powered-by` header but it refers to a particular implementation as opposed to the standard. One would have to then get the spec details out of band.

**Comment by RubenVerborgh** [comment]
Also see #221 #220

**Comment by csarven** [comment]
Continued in https://github.com/solid/specification/issues/179 .
