### ISSUE TITLE
Takedown requests / account deletion / privacy in a distributed and interactive web

### ISSUE THREAD

**Issue by joepio** [solid/solid-spec#224]
When I remove a social media account, I expect the service to delete my user data, my name, my ID and everything related to my activities. With Solid, most of my data will exist only in my own POD. Deleting my POD will therefore result in deleting most of my data. However, when I use some interactive feature elsewhere (e.g. posting comments in a solid-powered forum), I might still create pieces of personal information outside of my pod.

I think it makes sense to include a type of takedown requests in the Solid spec. These takedown requests should only be acceptable from a verified source (only my WebID should be able to issue a valid takedown request for my data). Perhaps users should be able to decide whether their content should be _deleted_ or _anonymized_.

**Comment by csarven** [comment]
I think it'd be most valuable to raise this in the form of a user story in https://github.com/solid/user-stories . Doublecheck for duplicates and related issues.

Note that the current work on the Solid specification is carried out in https://github.com/solid/specification . Some of requirements that can be expected from this issue are already looked into there.
