### ISSUE TITLE
Post vs. Ping to shared data space + assigning graph names

### ISSUE THREAD

**Issue by elf-pavlik** [solid/solid-spec#26]
I would like to discuss different approaches to post to group / shared data spaces. To my understanding SoLiD currently recommends direct HTTP POST to such shared data space.

![post to shared space](https://docs.google.com/drawings/d/1htmTGk1C26buCUYkqYVittNUwM8VrRaz1B7CSJJGdRg/pub?w=960&h=720)

IndieWeb for contrast, always recommends to publish in your personal data space first and then ping other space to request transclusion of your content you published independently.

![ping to shared space](https://docs.google.com/drawings/d/1m_vnTSa0ewGmnu2wJOhpzRXrKZT2VAnmCZwvXqEFNTU/pub?w=960&h=720)

I find it especially interesting to analyze graph names shared dataspace could assign in those two scenarios. 

1) URI of container in shared data space Alice directly POST-ed to
2) URI of webmention endpoint which Alice POST-ed to requesting transclusion
3) URI of resource in Alice's personal data space used in webmention as *source* param
4) URI of Alice's identity

Since data could easily get duplicated in multiple graphs if needed. I find it especially attractive to maintain additional named graph per each identity. Which possibly could have the same state in shared data space, no matter if we use direct Post or Ping approach.

seeAlso: http://webmention.org (https://github.com/converspace/webmention/issues/40)

**Comment by melvincarvalho** [comment]
SoLiD can make use of either pattern.  Personally I am reminded in programming of "call by value" and "call by reference".  Most functions in most programming languages an handle either.  Each pattern being useful in different situations.  In general, in standards a good rule of thumb is "dont restrict unless you need to".  @elf-pavlik do you have a strong personal preference, in this respect?  Is there anything we could implement in SoLiD to make life easier?

**Comment by elf-pavlik** [comment]
So far I see one serious issue with Ping based pattern (inc. webmention) approach. If resource has ACL, the system receiving a ping will simply not have possibility to access that particular resource :S Ping could include some special token (eg. Bearer) in a payload but then Web Access Control would need to support such special cases.

**Comment by aaronpk** [comment]
@elf-pavlik see http://indiewebcamp.com/private-webmention for how I'm thinking of handling access-controlled content with webmention

**Comment by elf-pavlik** [comment]
@aaronpk thx! where we can have an async conversation about private-webmention? Maybe https://github.com/converspace/webmention/issues ping @fkooman

**Comment by dmitrizagidulin** [comment]
Closing, the discussion seems to be out of scope for the current Solid project. If there are action items or a concrete proposal here that I've missed, please open an issue on [solid/issues](https://github.com/solid/solid/issues).
