### ISSUE TITLE
Account Creation

### ISSUE THREAD

**Issue by bblfish** [solid/solid-spec#27]
The account creation example seems to create a special case where JSON is sent instead of JSON-LD.
It would be good to have something more LDP compatible.

It would be better in that it would avoid inventing new concepts if account creation be just a special form of LDPC. We did that with rww-play where creation on the root would create sub domains. This should not be so surprising as @timbl has stated that the one error he thinks on the web was the order of the domains which would have better been `io.rww` instead of the actual `rww.io`. In that way one can understand why POSTing to a `rww.io` would create a subdomain `bblfish.rww.io`, since if the domain order would be inversed `io.rww` would create `io.rww.bblfish`. LDPC's do allow domains to be created where the name is not inside the container. IE LDP Containers are not [Intuitive Containers](http://www.w3.org/2012/ldp/track/issues/50) - though that may be something nice to specify for LDP next. Still in this case it is helpful that LDPCs are not intutive containers.

**Comment by bblfish** [comment]
Some issues: 
* POSTing to a Container with a Slug returns a resource that if it clashes returns a name that may not be desired by the client.
* Perhaps one needs an [intuitive container](http://www.w3.org/2012/ldp/track/issues/50) where an account is created inside the container with PUT, which creates a resource which either creates the account there, points to the final account, or redirects to it. ( not sure )

**Comment by dmitrizagidulin** [comment]
Account creation no longer uses JSON instead of JSON-LD.

The general issue has moved to [solid/#57-Do we need APIs for account management?](https://github.com/solid/solid/issues/57). Closing.
