### ISSUE TITLE
split SoLiD spec into mini specs

### ISSUE THREAD

**Issue by bblfish** [solid/solid-spec#36]
The SoLiD spec is a bit long to read in one go. It would be better to split it along smaller documents each orthogonal to the other. Then there could be a table listing which of these specs were implemented by which platforms, and use that to guide future working groups.

**Comment by deiu** [comment]
Good idea. I will attempt to do this progressively.

**Comment by rhiaro** [comment]
@deiu I don't have time imminently, but I'd be interested in helping with this as part of the process of understanding the spec better. I attempted [something similar for ActivityPump](https://github.com/w3c-social/activitypump/blob/master/implementation.md) a bit ago.

**Comment by deiu** [comment]
@rhiaro that would awesome, thank you! It's no rush though.

**Comment by sebilasse** [comment]
In general I like the idea of "stories" (*user first*) and I would recommend to mention 
the https://melvincarvalho.gitbooks.io/solid-tutorials/
in https://github.com/solid/solid-spec/tree/master/UserStories
[or merge them]
and btw (hopefully you get the humour) : In the story
https://github.com/solid/solid-spec/blob/master/UserStories/UserProfileManagement.md
could we replace ```kim``` by ```tim``` ?

**Comment by dmitrizagidulin** [comment]
Implemented as of PR https://github.com/solid/solid-spec/pull/87. Closing.
