### ISSUE TITLE
How does SoLiD plan to deal with 'application/activity+json' ?

### ISSUE THREAD

**Issue by akuckartz** [solid/solid-spec#39]
Background for this question:
https://www.w3.org/wiki/Socialwg/2015-07-07-minutes#Github_Issue_86:_Add_.60application.2Fld.2Bjson.60_as_requirement_for_servers

My current suggestion is to object to 'application/activity+json' and propose to require 'application/ls+json' plus profile instead. As @bblfish stated this does not solve all serialization issues but it would be better than creating an unnecessary new media type.

**Comment by deiu** [comment]
Our two SoLiD servers (gold and ldnode) both support JSON-LD (application/ld+json).

**Comment by akuckartz** [comment]
This issue is about the current requirement by Activity Streams 2.0 to support a new special Activity Streams 2.0 media type instead of the JSON-LD media type (with a profile).

**Comment by deiu** [comment]
I see. I believe it is less likely that SoLiD will support the `application/activity+json` media type, at least in the near future.

**Comment by sandhawke** [comment]
It should be fine to accept it as a synonym for json-ld during writes.   The question is when it's okay to serve it, and I'm not exactly clear about that.   What is the subset of json-ld that is also activity+json.  Hmmm.

**Comment by sebilasse** [comment]
@deiu 

I have a couple of additional questions related to JSON :
In this [talk](https://www.youtube.com/watch?v=yi4SgNyDJ9w) it was said that it only depends on the URI ...
However – to have an idempotent and restful "JSON handling" the spec. should allow that

> PATCH with sparql-update

could also be [JSON Patch](https://tools.ietf.org/html/rfc6902)
and how about 

> Link: <https://example.org/data/.meta>; rel="describedby"

- Could this also be a [JSON schema](http://json-schema.org): 
RFC [core](http://json-schema.org/latest/json-schema-core.html), [validation](http://json-schema.org/latest/json-schema-validation.html), [hyper-schema](http://json-schema.org/latest/json-schema-hypermedia.html) ?

**Comment by bblfish** [comment]
`PATCH`  with Json Patch on an LDP server is something that would be possible, but it would require a server to be able to keep a stable copy of the serialisation of the data. It would also require the client to keep a very good copy of the serialised data without moving it. Different parsers in JS act quite differently, so it may not be very reliable. In any case once you build Linked Data apps you'd on the whole like to get away as far as possible from serialisations. It is costly to maintain on the client and the server

**Comment by dmitrizagidulin** [comment]
Closing. Moving to:

- [solid/#82-JSON Patch support](https://github.com/solid/solid/issues/82)
- [solid/#83-AS2 Integration / support for 'application/activity+json' content type](https://github.com/solid/solid/issues/83)
