### ISSUE TITLE
Social API brainstorming page

### ISSUE THREAD

**Issue by akuckartz** [solid/solid-spec#41]
Some of the tables in the Social API brainstorming page are missing a column for SoLiD: https://github.com/w3c-social/Social-APIs-Brainstorming/blob/master/socialapi.md

**Comment by deiu** [comment]
Some of the missing columns are not applicable in the case of SoLiD. For instance, the Publishing section is application-specific in the case of SoLiD.

**Comment by dmitrizagidulin** [comment]
Closing - sounds like the Social API activity has moved on to https://github.com/w3c-social/social-web-protocols/issues (and this issue belongs there).
