### ISSUE TITLE
Solid needs a logo

### ISSUE THREAD

**Issue by nicola** [solid/solid-spec#43]
Sorry to be trivial.. :dancer:

**Comment by melvincarvalho** [comment]
see

https://avatars3.githubusercontent.com/u/14262490?v=3&s=200

**Comment by csarven** [comment]
Question to answer: what impression/idea should the logo give?

Very brief brainstorm:

* "solid" as in "doing a solid", a favour. What would that look like?
* "solid" as in hard/stable. "re: Melvin's draft; besides the colour, I see it like a bolt or a screw -- that can go in that direction.
* countless ideas on the triple idea
* countless ideas on social/speech/community ideas
* ...

I generally prefer simple 2d logos (without shadows, gradients, ...) with a single colour. Rule of thumb: should be fax-machine safe ;)

**Comment by sandhawke** [comment]
Melvin's is very nuts-and-bolts, which I like.  It also has the pointy brackets of HTML and Turtle, like the Polymer logo.   In plaintext one might write it as <s>.

**Comment by melvincarvalho** [comment]
FYI: this wasnt "my" logo, I just noticed it in github and pasted it here :)

**Comment by nicola** [comment]
I was expecting something more.. flat, either:

- "solid" a-la matrix.org
- <s>
- or even an S made of 6 dots joint by lines (like the linked data logo but with more dots)
- or somehting HTML5-esque like a shield for the open web or similar

**Comment by deiu** [comment]
The logo Melvin linked earlier was made by our Guillaume a few weeks ago.

**Comment by csarven** [comment]
@deiu Can we have the original in SVG available in the repo?

**Comment by deiu** [comment]
@csarven done. b110e4add2a90c79d43844df8d121fbb7fe4d83e

**Comment by sandhawke** [comment]
It would be good to have a way of writing it that includes the rest of the word, or something, so it makes some sense to folks who are not already entirely familiar with it.

**Comment by csarven** [comment]
There are two distinct uses and we need both: lettering (with or without objects) and object(s) alone. The current logo with the "S" covers the latter case, good for limited spaces, avatars, favicons etc. When space permits, we should have the lettering with the complete word (as @sandhawke suggests) e.g., SoLiD homepage.

IMO, good lettering / typeface use is of top most importance. For example, depending on the typeface, the "S" of SoLiD can become the stand-alone representative object, which would be used in limited spaces. I think deriving the "object" from the lettering is a good aim to have. Maintains consistency..

This also feeds right into designing interfaces with responsive logos.

**Comment by akuckartz** [comment]
I would like to see some similarity with the established RDF / Semantic Web logos.

**Comment by deiu** [comment]
@csarven good points!

@akuckartz why does it have to be similar to existing RDF logos? Now that I think about it, I'm not even sure if we should mention Linked Data in the name.

**Comment by nicola** [comment]
@deiu this is the point I was making when saying that Solid shouldn't necessarily mean either Social or Linked Data

**Comment by deiu** [comment]
Lately I've started talking about it in terms of "a Solid attempt to re-decentralize the Web" :)

**Comment by akuckartz** [comment]
It does not "have to be" similar, but SoLiD rests on historic technical foundations which it does not need to hide.

**Comment by sandhawke** [comment]
And there are many, many other attempts at decentralization.  What makes this one stand out is its use of RDF linked data, I think.

**Comment by melvincarvalho** [comment]
Actually I think RDF is a detail.  It could be swapped out, IMHO, with another technology that had the same properties ie [web axioms](http://www.w3.org/DesignIssues/Principles.html) such as universality, modularity etc. but there's not really a viable alternative, at least that Im aware of, right now.  

To my mind SoLiD is more like the "web done right" than "linked data done right", at least, what I have read and interpreted from the original goals in [design issues](http://www.w3.org/DesignIssues/), and weaving the web.  What excites me from those two works is the vision that anything could be connected to anything (which is where RDF comes in).  For me, where SoLiD really shines is adding powerful missing features that exist in operating systems such as access control and realtime processing.

**Comment by deiu** [comment]
Indeed, +1.

**Comment by nicola** [comment]
The logo that @melvincarvalho references to is now the official logo till new proposals
