### ISSUE TITLE
top level assets

### ISSUE THREAD

**Issue by melvincarvalho** [solid/solid-spec#48]
I was wondering if we should move assets such as : 

https://github.com/solid/solid-spec/blob/master/solid_logo.svg

Into their own directory.  I have a diagram I'd like to upload too:

https://test.databox.me/Public/test.svg

Would be good to put such things in the same place, just need to agree on a directory name.  Thoughts?

**Comment by deiu** [comment]
Short answer...yes! :)

**Comment by deiu** [comment]
Closed by ae1e870328ed0ba2dd302352422cd1009689010c
