### ISSUE TITLE
semantic pingback/webmention

### ISSUE THREAD

**Issue by bblfish** [solid/solid-spec#53]
There is a discussion on semantic pingback/webmention going on here https://github.com/w3c-social/webmention/issues/3 

Pointing to some agreed on vocabularies would be very useful, but could make the spec way too long. This argues for [splitting the spec up](https://github.com/solid/solid-spec/issues/36), with the front page consisting of an overview and an index to the other parts.

**Comment by gobengo** [comment]
Am I right in understanding that so far solid has not proposed an alternative to webmention/pingback?

If so, great. Perhaps that is something to work on together. And solid could use it too.

**Comment by melvincarvalho** [comment]
I tend to agree with @bblfish that pingback doesnt need to go in the core spec.  I think Solid would work just fine with semantic pingback or any number of ping / notification type technologies.  Solid does have realtime support for notifications via websockets in the core spec.

I'd suggest this might be slightly more at the the application level.  If anyone is working on an app that uses this kind of technology it would be interesting to see that documented, and then see how it relates to the spec.

Alternatively, Solid has a section on the social web user stories.  That may be a good place to for someone to explore this further:

https://github.com/solid/solid-spec/tree/master/UserStories

I suspect that we will get a better idea of how useful this is as apps which might use this or similar functionality are built.

**Comment by bblfish** [comment]
Well I think it would be better to cut the spec up into modules, indexed from the main page with short explanations and to have a page listing implementations of each module. I don't think that the websocket notification does the same as pingback. That requires I think the client to be online to receive notifications. The Pingback allows a notification to be sent to a server without that server being required to keep an open connection. ( but I may be wrong )

**Comment by bblfish** [comment]
The discussion on web-mention was closed https://github.com/w3c-social/webmention/issues/3 due to Social Web WG policy battle it seems. But some of the points that came up there are good, and we can continue the work here.

**Comment by csarven** [comment]
I think this issue has been resolved as Solid inbox/notification was in proposal, which later became LDN as its own spec. I suggesting closing.

**Comment by kjetilk** [comment]
Yes, it sounds like we don't want out own mechanism for this.

**Comment by csarven** [comment]
Closing this as out of scope. There has been no form based processing baked into Solid/LDP servers or any plans for it.
