### ISSUE TITLE
Ability to HTTP Patch the response headers 

### ISSUE THREAD

**Issue by csarven** [solid/solid-spec#58]
I may really be over thinking or looking something but:

If it isn't already possible, I think it'll be useful to be able to PATCH only the headers, e.g., `Link`. GETing the complete response, processing it, and then sending it all back to the server doesn't feel right for a number of reasons - most obvious one being that it will introduce unintended diffs.

**Comment by gobengo** [comment]
I don't doubt that there is one, but I'm curious what your use case for this is? ie which headers are you interested in changing?

One could think of the headers as a different logical resource like
for
`/container-1/resource/`
the headers would be
`/container-1/.meta/resource/headers`

**Comment by csarven** [comment]
I had `Link` in mind when I wrote that but neglected to mention it. Updated original comment.

One UC that I ran into was that was with ripples / pingbacks / notifications in which they indicate where the container is in the case of Link headers with `rel="pingback:to"`.

I think it is better to keep the pingback (e.g., the rel="pingback:to" assignment) outside of the core Solid spec. That is so that implementations need not need to hardcode that relation by automatically setting it for the container's header every time the container is created or updated. If we subscribe to that idea, then what that leaves us is a way to enable the client who has the priviledges to that resource to set (or lets say propose) that link relation. The server can decide whether it is of interest or allowed in any case, just as it does with `ldp:Container` and `ldp:Resource`.

See also: https://lists.w3.org/Archives/Public/public-ldpnext/2015Dec/0002.html

**Comment by deiu** [comment]
I'm against this feature, as it opens up the door to abuse. Solid uses Link headers as part of the protocol -- i.e. to indicate where ACLs are, who the logged in user is, etc. Applications trust that **only** the server can set those links, and they can't be modified. Perhaps we can achieve a similar behavior setting a triple in the meta file.

**Comment by csarven** [comment]
@timbl said the following at https://gitter.im/linkeddata/gold

> @csarven Behind this question of link headers some important architectural points
>* The headers are communication between client and server cde, they are there to facilitate the communication of content data betwen a clients.
>* A server (or client) has to understand what the header means, or it ignores it.
>* This means someone can come along in he future and say “when I send a link hrader rel=greendudge in a put with this value it means the server should read that linked resource too and return if it has an odd number of bytes”. They know that any pastimplementations will ignotre it as they don’t understand it
>* The data communicated between clients via web storage is all in the “entity”, the content part of the HTTP message, interpret with the aid of the content-ytpe header.
>* The server ignores what is stored in the contents. SO clienst can exchange whatever they like without side effects.

> These are important architecural invariants. They are similar to the unic file system ones, apart from content-type being explicit.

> The unix file system has many nice properties (files are just byte arrays or directories, etc) and has been useful because its simplicity has allowed lost things to be built on top of it. The solid architecture should be as simple as possible too. Adding things which improve it like content-type but adding as fwe things at the HTTP header level as possible.

> So store the link in the file!

**Comment by csarven** [comment]
I'm content to drop this request given information above. The original intention was to come half-way and see whether it makes sense to introduce this sort of information in the header. Letting the resource content speak for itself is preferable (at least for me).

**Comment by csarven** [comment]
@deiu FYI: The original UC was based on the draft [pingback/ripples](https://github.com/solid/solid-spec/blob/master/ripples.md) in which if an agent wants to enable a container to receive pingbacks, it might want to have the option to do that via the `Link` header - that's okay, there are alternatives. That would have been either a PATCH, or "setting" it via POST/PUT. As a fallback, the server can either set the pingback relation automatically (which I don't particularly like) every time a container is created, or it will be there available from the start when the workspaces are first created.

**Comment by csarven** [comment]
HTTP LINK method: http://tools.ietf.org/html/rfc2068#section-19.6.1.2
