### ISSUE TITLE
ACL Groups infinite loops

### ISSUE THREAD

**Issue by nicola** [solid/solid-spec#71]
Consider this scenario:

- Server A
  - Groups/WorkingGroup.ttl
  - Groups/WorkingGroup.ttl.acl (it says `only B/Groups/Admins.ttl can read!`)

- Server B
  - Groups/Admins.ttl
  - Groups/Admins.ttl (it says `only A/Groups/WorkingGroup.ttl can read!`)
  - Work/File.ttl
  - Work/File.ttl.acl (it says `only A/Groups/WorkingGroup.ttl can read!` )

Now, when one tries to access any file where `WorkingGroup` or `Admins` can read (e.g. `B/Work/File.ttl.acl`), each server will ask the other to read the group, which will need to ask the other to read the Group to read the permission to read the Group, but then the server will ask back to read the other Group to read the other group permissions and so on, in an infinite loop.

Currently affects gold, I have commented out groups in `ldnode`

**Comment by dmitrizagidulin** [comment]
Moving to https://github.com/solid/solid/issues/8 as a result of the [solid project workflow discussion](https://github.com/solid/solid-spec/issues/75). Closing.
