### ISSUE TITLE
Consider Mechanism to upgrade insecure requests

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/solid-spec#73]
(moving here from https://github.com/linkeddata/gold/issues/70, originally opened by @csarven).

https://www.w3.org/TR/upgrade-insecure-requests/ puts forward "a mechanism which allows authors to instruct a user agent to upgrade a priori insecure resource requests to secure transport before fetching them."

This is a handy feature to get around some of the mixed content issues.

**Comment by deiu** [comment]
I wonder if this is a real issue for us. Mixed content problems appear when you have an application that runs on HTTPS and you're trying to fetch resources over HTTP. The Web is moving to HTTPS, and Solid is no exception. Both ldnode and gold run first and foremost over HTTPS, which means that clients won't risk getting mixed content warnings when fetching resources from them. I think it's the rest of the Web that rather needs to implement the upgrade mechanism.

**Comment by csarven** [comment]
This is particularly about error prevention, and how Solid can foster a friendly UX. It is not directly a Solid platform issue b/c it has to do with the data - which may exist and retrieved from anywhere. Hence, I labelled the original issue as a feature. I think the core concern is that, for the foreseeable future, it is _likely_ that applications which run on https uses data with http references.

**Comment by deiu** [comment]
Yes, but there is nothing we can do on our side. It's about moving to HTTPS.

**Comment by deiu** [comment]
Closing this issue since it doesn't involve an action on our part.
